# Default values for furan.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 8
maxSurge: 25%
maxUnavailable: 25%
env: qa
image:
  repository: quay.io/dollarshaveclub/furan
  tag: master
  pullPolicy: Always
  pullSecrets: image-pull-secrets

service:
  create: true
  type: ClusterIP

  httpInternalPort: 4000
  httpExternalPort: 4000
  httpServiceName: http

  grpcInternalPort: 4001
  grpcExternalPort: 4001
  grpcServiceName: grpc

  httpHealthcheckPort: 4002
  httpHealthcheckPath: /health
  performanceProfilingPort: 4003

dbNodes: "scylladb"
kafkaBrokers: "kafka-furan:9092"

vault:
  addr: "http://vault:8200"
  token: "root"

consulAddr: "consul:8500"

ramdisk:
  enabled: false

app:
  useNewRelic: false
  newRelicAppName: furan-dev

dnsPolicy: ClusterFirst
dnsConfig: {}
